### ISSUE TITLE
bug in SHA1_Update()

### ISSUE THREAD

**Issue by chen-bob** [odzhan/tinycrypt#1]
void SHA1_Update (SHA1_CTX *c, void *in, uint32_t len) {
  ......
  
  while (len > 0) {
    r = len >= SHA1_CBLOCK ? SHA1_CBLOCK : len;  // should change to: r = min(len, SHA1_CBLOCK - idx);
   ......
  }
}

**Comment by odzhan** [comment]
Hello!

Thank you for reporting this problem. Code has been updated.
